
setwd('/ketcindy.git/myfiles/arrowR')
source('/Applications/kettex/texlive/texmf-dist/scripts/ketcindy/ketlib/ketpiccurrent.r')
Ketinit()

Wfile="ketlayermorewith2e.sty"
cat("%20201024\n",file=Wfile)

Texnewcmd("\\qarrow",5,12)
Texcom("{\\unitlength=0.01mm")
Texcom("\\begin{picture}(0,0)(0,0)")
Texsetctr(1,"(-1)*#3*#3/4+2500")
Texsetctr(2,"100*#3/2")
Texsetctr(3,"#3*#3/4+2500")
Texsetctr(4,"(-1)*#5*#5/4+2500")
Texsetctr(5,"100*#5/2")
Texsetctr(6,"#4*Texctr(5)/Texctr(4)")
Texsetctr(4,"Texctr(6)")
Texsetctr(5,"#4*Texctr(1)/Texctr(3)")
Texsetctr(6,"Texctr(4)*Texctr(2)/Texctr(3)")
Texsetctr(5,"-Texctr(6)")
Texsetctr(6,"#4*Texctr(2)/Texctr(3)")
Texsetctr(7,"Texctr(4)*Texctr(1)/Texctr(3)")
Texsetctr(6,"+Texctr(7)")
Texsetctr(7,"#4*Texctr(1)/Texctr(3)")
Texsetctr(8,"Texctr(4)*Texctr(2)/Texctr(3)")
Texsetctr(7,"+Texctr(8)")
Texsetctr(8,"#4*Texctr(2)/Texctr(3)")
Texsetctr(9,"Texctr(4)*Texctr(1)/Texctr(3)")
Texsetctr(8,"-Texctr(9)")
Texsetctr(9,"Texctr(5)+Texctr(7)")
Texsetctr(9,"/2*8/10");
Texsetctr(10,"Texctr(6)+Texctr(8)")
Texsetctr(10,"/2*8/10");
Texcom("\\linethickness{0.001 in}")
tmp=paste("\\polygon*(0,0)(",Texthectr(5),",",Texthectr(6),")(",sep="")
tmp=paste(tmp,Texthectr(9),",",Texthectr(10),")(",sep="")
tmp=paste(tmp,Texthectr(7),",",Texthectr(8),")(0,0)",sep="")
Texcom(tmp)
Texsetctr(9,"#2*100/2");
Texsetctr(10,"#2*100/2*Texctr(2)/Texctr(1)");
Texsetctr(4,"#2*100");
Texsetctr(1,"Texctr(5)+Texctr(7)")
Texsetctr(1,"/2*8/10");
Texsetctr(2,"Texctr(6)+Texctr(8)")
Texsetctr(2,"/2*8/10");
Texsetctr(9,"+Texctr(1)")
Texsetctr(10,"+Texctr(2)")
Texif("#1<10")
  Texcom("\\linethickness{0.00#1 in}")
Texelse()
  Texcom("\\linethickness{0.0#1 in}")
Texendif()
tmp1=paste("(",Texthectr(1),",",Texthectr(2),")",sep="")
tmp2=paste("(",Texthectr(9),",",Texthectr(10),")",sep="")
tmp3=paste("(",Texthectr(4),",",Texthectr(2),")",sep="")
tmp=paste("\\qbezier{",tmp1,tmp2,tmp3,"}",sep="")
Texcom(tmp)
Texcom("\\end{picture}}")
Texend()

Texnewcmd("\\qarrowlinefull",8,12)
Texcom("%thick,x,y,length,angle,ctr,size,tan(arrow/2)*1000")
Texcom("\\putnotese{#2}{#3}{")
Texcom("\\rotatebox[origin=l]{#5}{\\qarrow[#1]{#4}{#6}{#7}{#8}}}")
Texend()

Texnewcmd("\\qarrowlinesize",7,12)
Texcom("%thick,x,y,length,angle,ctr,size")
Texcom("\\qarrowlinefull[#1]{#2}{#3}{#4}{#5}{#6}{#7}{16}")
Texend()

Texnewcmd("\\qarrowline",6,12)
Texcom("%thick,x,y,length,angle,ctr")
Texcom("\\qarrowlinefull[#1]{#2}{#3}{#4}{#5}{#6}{200}{16}")
Texend()

Texrenewcmd("\\arrowlineseg",5,12)
Texcom("%thick,x,y,length,angle")
Texcom("\\qarrowlinefull[#1]{#2}{#3}{#4}{#5}{0}{200}{16}")
Texend()
